swagger: "2.0"
info:
  title: INEZ-API - Der INtelligente EinkaufsZettel
  description: 'Dokumentation der API des INtelligenten EinkaufsZettel (INEZ)'
  contact:
    email: "w.d@mail.de"
  version: 1.0.0
basePath: "/api"
tags:
- name: "user"
  description: "User"
- name: "grocerylists"
  description: "Grocerylists"
- name: "list"
  description: "list"
schemes:
- "https"
- "http"
paths:
  /user:
    get:
      tags:
      - "user"
      summary: "Gibt die Informationen des angemeldeten Users zurück"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
      responses:
        200:
          description: "Informationen des Users"
          schema:
            type: "object"
            properties:
              userName:
                type: "string"
                example: "user01"
        505:
          description: "Internal Server Error"
        401:
          description: "Registrieren fehlgeschlagen"
  /user/register:
    post:
      tags:
      - "user"
      summary: "Registriert den User"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "user"
          description: "The user to create."
          schema:
            type: "object"
            required:
              - "userName"
            properties:
              userName:
                type: "string"
                example: "user01"
              password:
                type: "string"
                example: "treppe123"
      responses:
        200:
          description: "JWT"
          schema:
            type: "object"
            properties:
              jwt:
                type: "string"
                example: "13adwa942839rj2iuhr23i9"
        505:
          description: "Internal Server Error"
        401:
          description: "Registrieren fehlgeschlagen"
  /user/login:
    post:
      tags:
        - "user"
      summary: "Meldet den User an"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "user"
          description: "The user to create."
          schema:
            type: "object"
            required:
              - "userName"
              - "password"
            properties:
              userName:
                type: "string"
                example: "user01"
              password:
                type: "string"
                example: "treppe123"
      responses:
        200:
          description: "JWT"
          schema:
            type: "object"
            properties:
              jwt:
                type: "string"
                example: "13adwa942839rj2iuhr23i9"
        505:
          description: "Internal Server Error"
        401:
          description: "Login fehlgeschlagen"
          
  /lists:
    get:
      tags:
        - "grocerylists"
      summary: "Gibt alle Listen des Users zurück"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
      responses:
        200:
          description: "Einkaufslisten"
          schema:
            type: "object"
            properties:
              grocerylists:
                type: "array"
                items:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                    creationDate:
                      type: "string"
                example:
                  - name: "Einkaufsliste1"
                    creationDate: "12.12.12"
                  - name: "Einkaufsliste2"
                    creationDate: "13.12.19"
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
    put:
      tags:
        - "grocerylists"
      summary: "Erstellt eine Liste"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "body"
          name: "user"
          description: "Die liste die angelegt werden soll."
          schema:
            type: "object"
            required:
              - "listname"
            properties:
              listname:
                type: "string"
                example: "Einkaufsliste1"
      responses:
        200:
          description: "Angelegte Liste"
          schema:
            type: "object"
            properties:
              listname:
                type: "string"
                example: "Einkaufsliste1"
              creationDate:
                type: "string"
                example: "13.12.19"
                
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
    delete:
      tags:
        - "grocerylists"
      summary: "Löschte eine liste"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "body"
          name: "user"
          description: "Die Liste die angelegt werden soll."
          schema:
            type: "object"
            required:
              - "listname"
            properties:
              listname:
                type: "string"
                example: "Einkaufsliste1"
      responses:
        200:
          description: "Name der gelöschten liste"
          schema:
            type: "object"
            properties:
              listname:
                type: "string"
                example: "Einkaufsliste1"
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
          
  /lists/{listname}:
    get:
      tags:
      - "list"
      summary: "Gibt die Gruppen der Liste zurück, sowie die elemente der Gruppe"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "path"
          name: "listname"
          required: true
          type: "string"
      responses:
        200:
          description: "Gruppen der Liste mit Elementen der Gruppe"
          schema:
            type: "object"
            properties:
              groceryGroups:
                type: "array"
                items:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                    groceryItems:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          productname: "string"
                          amount: "int"
                          measure: "string"
                          checked: "boolean"
                example:
                  - name: "Gruppe1"
                    groceryItems:
                      - productname: "produkt"
                        amount: 1000
                        measure: "gramm"
                        checked: true
                  - name: "Gruppe1"
                    groceryItems:
                      - productname: "produkt"
                        amount: 0
                        measure: ""
                        checked: false
                      - productname: "produkt2"
                        amount: 2
                        measure: "kg"
                        checked: true
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
  /lists/create:
    put:
      tags:
      - "list"
      summary: "Erstellt eine Gruppe"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "body"
          name: "user"
          description: "Die Gruppe die angelegt werden soll."
          schema:
            type: "object"
            required:
              - "groupname"
            properties:
              groupname:
                type: "string"
                example: "Edeka"
      responses:
        200:
          description: "Name der erstellten Gruppe"
          schema:
            type: "object"
            properties:
              groupname:
                type: "string"
                example: "Edeka"
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
  
  /lists/delete:
    delete:
      tags:
      - "list"
      summary: "Löscht eine Gruppe"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "body"
          name: "user"
          description: "Die Gruppe die gelöscht werden soll."
          schema:
            type: "object"
            required:
              - "groupname"
            properties:
              groupname:
                type: "string"
                example: "Edeka"
      responses:
        200:
          description: "Name der gelöschten Gruppe"
          schema:
            type: "object"
            properties:
              groupname:
                type: "string"
                example: "Edeka"
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
          
  /lists/{listname}/{groupname}:
    put:
      tags:
      - "list"
      summary: "Fügt ein Produkt einer Gruppe hinzu"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "path"
          name: "listname"
          required: true
          type: "string"
        - in: "path"
          name: "groupname"
          required: true
          type: "string"
        - in: "body"
          name: "user"
          description: "Das Produkt das hinzugefügt werden soll."
          schema:
            type: "object"
            required:
              - "productname"
            properties:
              productname:
                type: "string"
                example: "Milch"
              amount: 
                type: "number"
                example: 100
              measure: 
                type: "string"
                example: "gramm"
              checked:
                type: "boolean"
                example: false
      responses:
        200:
          description: "Hinzugefügtes element"
          schema:
            type: "object"
            properties:
              productname:
                type: "string"
                example: "Milch"
              amount: 
                type: "number"
                example: 100
              measure: 
                type: "string"
                example: "gramm"
              checked:
                type: "boolean"
                example: false
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
        423:
          description: "Produkt existiert bereits in der Gruppe"
    post:
      tags:
      - "list"
      summary: "Updatet das gegebene Produkt (Key: Produktname) mit den gegebenen Werten."
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "path"
          name: "listname"
          required: true
          type: "string"
        - in: "path"
          name: "groupname"
          required: true
          type: "string"
        - in: "body"
          name: "user"
          description: "Das Produkt das geupdated werden soll"
          schema:
            type: "object"
            required:
              - "productname"
            properties:
              productname:
                type: "string"
                example: "Milch"
              amount: 
                type: "number"
                example: 100
              measure: 
                type: "string"
                example: "gramm"
              checked:
                type: "boolean"
                example: false
      responses:
        200:
          description: "Element mit geupdatetem Werten"
          schema:
            type: "object"
            properties:
              productname:
                type: "string"
                example: "Milch"
              amount: 
                type: "number"
                example: 100
              measure: 
                type: "string"
                example: "gramm"
              checked:
                type: "boolean"
                example: false
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"
    delete:
      tags:
      - "list"
      summary: "Löscht das gegebene Produkt (Key: Produktname)"
      parameters:
        - in: "header"
          name: "jwt"
          description: "JSON-Web-Token"
          type: "string"
        - in: "path"
          name: "listname"
          required: true
          type: "string"
        - in: "path"
          name: "groupname"
          required: true
          type: "string"
        - in: "body"
          name: "user"
          description: "Das Produkt das gelöscht werden soll"
          schema:
            type: "object"
            required:
              - "productname"
            properties:
              productname:
                type: "string"
                example: "Milch"
      responses:
        200:
          description: "Name des gelöschten elements"
          schema:
            type: "object"
            properties:
              productname:
                type: "string"
                example: "Milch"
        505:
          description: "Internal Server Error"
        401:
          description: "JWT nicht gültig"